- name: Install packages
  yum: name={{item}} state=installed
  with_items:
    - wget
    - git
    - python-pip

- pip:
    name: psycopg2
    executable: pip

- name: Create gogs database
  postgresql_db: 
    name: gogs

- name: wget
  get_url:
    url: https://dl.gogs.io/0.11.34/linux_amd64.tar.gz
    dest: /root/

- unarchive:
    src: /root/linux_amd64.tar.gz
    dest: /root/
    remote_src: True

- name: Add user gogs
  shell: adduser gogs